#!/usr/bin/env bash
dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config home"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    log "copying over files from: $1"
    pushd "$1" &> /dev/null || return
    (
        configs=$(find . -mindepth 1 -maxdepth 1)
        for c in $configs; do
            target="${2%/}/${c#./}"
            log "    removing: rm -rf $target"

            if [[ $dry_run == "0" ]]; then
                rm -rf "$target"
            fi

            log "    copying env: cp -r $c to $2"
            if [[ $dry_run == "0" ]]; then
                cp -r "./$c" "$2"
            fi
        done

    )
    popd &> /dev/null || return
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
update_files $DEV_ENV/env/.local $HOME/.local

copy $DEV_ENV/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy $DEV_ENV/env/.zsh_profile $HOME/.zsh_profile
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/env/.tmux-sessionizer $HOME/.tmux-sessionizer
[ -f $DEV_ENV/env/.Xresources ] && copy $DEV_ENV/env/.Xresources $HOME/.Xresources
[ -f $DEV_ENV/env/.gtkrc-2.0 ] && copy $DEV_ENV/env/.gtkrc-2.0 $HOME/.gtkrc-2.0

# Provide permissions
chmod +x $HOME/.local/scripts/* 2>/dev/null || true
chmod +x $HOME/.config/polybar/launch.sh 2>/dev/null || true
chmod +x $HOME/.config/polybar/scripts/* 2>/dev/null || true