#!/usr/bin/env bash

# Global Functions for Scripts #

# Update system before installing packages
sudo dnf update -y

# Function to install packages
install_package() {
  if rpm -q "$1" &>/dev/null ; then
    echo -e "$1 is already installed. Skipping..."
  else
    # Run dnf without progress or logging
    sudo dnf install -y "$1" 

    # Double check if package is installed
    if rpm -q "$1" &>/dev/null ; then
      echo -e "Package $1 has been successfully installed!"
    else
      echo -e "\n$1 failed to install. Please check manually."
    fi
  fi
}