#!/usr/bin/env bash
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

# Source the global functions script
if ! source "$script_dir/Global_functions"; then
  echo "Failed to source Global_functions"
  exit 1
fi

# Verify install_package exists
if ! declare -f install_package > /dev/null; then
    echo "Error: install_package function not found in Global_functions"
    exit 1
fi

# Export the install_package function
export -f install_package

export DEV_ENV="$DEV_ENV"

grep=""
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    else
        grep="$1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "RUN: env: $DEV_ENV -- grep: $grep"

runs_dir=$(find "$script_dir/runs" -mindepth 1 -maxdepth 1 -executable)

for s in $runs_dir; do
    if basename "$s" | grep -vq "$grep"; then
        log "grep \"$grep\" filtered out $s"
        continue
    fi

    log "running script: $s"
    if [[ $dry_run == "0" ]]; then
        bash -c "$s"  # Explicitly run in a new bash shell
    fi
done