#!/bin/bash

# Options for the power menu
options=" Lock\n Reboot\n Shutdown\n Suspend\n Logout"

# Show Rofi menu
selected=$(echo -e "$options" | rofi -dmenu -p "Power Menu" -i -theme ~/.config/rofi/mytheme.rasi)

# Handle the selected option
case $selected in
    " Lock")
        i3lock --show-failed-attempts -i ~/Pictures/wallpapers/lock.png
        ;;
    " Reboot")
        systemctl reboot
        ;;
    " Shutdown")
        systemctl poweroff
        ;;
    " Suspend")
        systemctl suspend
        ;;
    " Logout")
        i3-msg exit
        ;;
esac