#!/usr/bin/env bash

sudo dnf upgrade -y

# Install
sudo dnf install -y git go unzip lua lua-devel luarocks

# Install fonts
sudo dnf install jetbrains-mono-fonts fira-code-fonts

go install github.com/air-verse/air@latest

# Git global config
git config --global user.email "iamghulamazad@gmail.com"
git config --global user.name "Muhammad Ghulam Azad Ansari"


# Programming language
sudo dnf upgrade -y

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh


# Install icons pack
sudo dnf install papirus-icon-theme