#!/usr/bin/env bash

# Enable RPMFusion (free and non-free).
# sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo dnf install -y "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm" "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"


# Speed-up DNF Package Manager
# echo 'fastestmirror=True' | sudo tee -a /etc/dnf/dnf.conf
# echo 'max_parallel_downloads=10' | sudo tee -a /etc/dnf/dnf.conf

sudo dnf upgrade -y

# Install Nvidia Driver
sudo dnf install -y git nvidia-driver go unzip lua lua-devel luarocks libavcodec-freeworld

# Install fonts
sudo dnf install jetbrains-mono-fonts fira-code-fonts

go install github.com/air-verse/air@latest

# Git global config
git config --global user.email "iamghulamazad@gmail.com"
git config --global user.name "Muhammad Ghulam Azad Ansari"


# Programming language
sudo dnf upgrade -y

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh


# Install icons pack
sudo dnf install papirus-icon-theme