#!/usr/bin/env bash

# Update package index
sudo apt-get update

# Install required packages
sudo apt-get install -y git golang-go unzip lua5.4 liblua5.4-dev luarocks curl wget

# Enable universe repository for fonts (if not already enabled)
sudo add-apt-repository universe -y
sudo apt-get update

# Install fonts
sudo apt-get install -y fonts-jetbrains-mono fonts-firacode

# Install air using Go
go install github.com/air-verse/air@latest

# Git global config
git config --global user.email "iamghulamazad@gmail.com"
git config --global user.name "Muhammad Ghulam Azad Ansari"


# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh


# Install icons pack
sudo apt-get install papirus-icon-theme