#!/usr/bin/env bash
# This script installs Ghostty, a terminal emulator, on an Ubuntu 24.04 system.

# Update package index
sudo apt-get update

# Install prerequisites
sudo apt install -y libgtk-4-dev libadwaita-1-dev git blueprint-compiler gettext libxml2-utils build-essential


# Download and extract Zig
wget https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz -O /tmp/zig.tar.xz
tar -xvf /tmp/zig.tar.xz -C $HOME/.local

# Add Zig to PATH for this session
export PATH="$HOME/.local/zig-linux-x86_64-0.14.0:$PATH"

# Add Zig to PATH permanently (if not already in ~/.bashrc)
if ! grep -q 'export PATH=$PATH:$HOME/.local/zig-linux-x86_64-0.14.0' ~/.bashrc; then
    echo 'export PATH=$PATH:$HOME/.local/zig-linux-x86_64-0.14.0' >> ~/.bashrc
fi

# Clone Ghostty repository
git clone git@github.com:ghostty-org/ghostty.git $HOME/Alien/ghostty

# Build and install Ghostty
(
    cd $HOME/Alien/ghostty
    zig build -p $HOME/.local -Doptimize=ReleaseFast
)