#!/usr/bin/env bash

# Install useful utilities and development tools
pkgs=(
  unzip
  ripgrep
  pavucontrol
  xclip
  jq
  tldr
  shutter
  python3
  gimp
  fzf
  btop
  bc
  alsa-lib-devel
  curl
  vlc
  make
  cmake
  blueman
  fzf
  brightnessctl
  util-linux
  xdg-utils
  playerctl
  pavucontrol
  pipewire-alsa
  pipewire-utils
  network-manager-applet
  jq
)

# installing engine needed for gtk themes
for PKG1 in "${pkgs[@]}"; do
  install_package "$PKG1"
done

# ffmpeg \ -- no longer available in Fedora 39
# Install multimedia group
sudo dnf group install multimedia

printf "\n%.0s" {1..2}
