#!/usr/bin/env bash

sudo dnf -y upgrade

# Install useful utilities and development tools
sudo dnf -y install \
  ripgrep \
  pavucontrol \
  xclip \
  jq \
  tldr \
  shutter \
  python3 \
  gimp \
  fzf \
  btop \
  bc \
  alsa-lib-devel \
  curl \
  vlc \
  make \
  cmake \
  blueman \
  fzf \
  brightnessctl \
  util-linux \
  nwg-displays \
  nwg-look \
  xdg-utils \
  playerctl \
  pavucontrol \
  pipewire-alsa \
  pipewire-utils \
  network-manager-applet \
  jq \
  


# ffmpeg \ -- no longer available in Fedora 39
# Install multimedia group
sudo dnf group install multimedia
