#!/usr/bin/env bash

sudo dnf -y upgrade

# Install useful utilities and development tools
sudo dnf -y install \
  ripgrep \
  pavucontrol \
  xclip \
  jq \
  tldr \
  shutter \
  python3 \
  gimp \
  fzf \
  btop \
  bc \
  alsa-lib-devel \
  ffmpeg \
  curl \
  vlc \
  make \
  cmake