#!/usr/bin/env bash

sudo dnf -y upgrade

sudo dnf install -y neovim python3-neovim lua lua-devel luarocks

cargo install stylua

wget https://luarocks.org/releases/luarocks-3.11.1.tar.gz
tar zxpf luarocks-3.11.1.tar.gz
cd luarocks-3.11.1
./configure && make && sudo make install
sudo luarocks install luacheck


# For DAP (debugger)
go install github.com/go-delve/delve/cmd/dlv@latest
