#!/usr/bin/env bash

# i3
# sudo dnf install i3 i3status polybar rofi picom nitrogen

# Sway
# sudo dnf install -y sway waybar dunst wlogout rofi-wayland 

# Hyprland
hypr=(
  hyprland
  hypridle
  hyprlock
  waybar 
  wallust 
  hyprpaper 
  hyprshot 
  wlogout 
  rofi-wayland 
  nwg-displays 
  nwg-look
  cava
  SwayNotificationCenter
  pamixer
  swww
)

# Hyprland
printf "Installing Hyprland packages .......\n"
for HYPR in "${hypr[@]}"; do
  install_package "$HYPR" "$LOG"
done

printf "\n%.0s" {1..2}