#!/usr/bin/env bash

# XDG-Desktop-Portals #

xdg=(
  xdg-desktop-portal-hyprland
  xdg-desktop-portal-gtk
)

# XDG-DESKTOP-PORTAL-HYPRLAND
printf "Installing xdg-desktop-portal-hyprland\n\n" 
for xdgs in "${xdg[@]}"; do
  install_package "$xdgs"
done
    
printf "\n%.0s" {1..2}