#!/bin/bash
if ! command -v cal >/dev/null || ! command -v dunstify >/dev/null; then
    echo "Error: cal or dunstify not installed"
    exit 1
fi
TMP=${XDG_RUNTIME_DIR:-/tmp}/"$UID"_calendar_notification_month
touch "$TMP" || { echo "Error: Cannot create $TMP"; exit 1; }
DIFF=$(<"$TMP")
: "${DIFF:=0}"
case $1 in
    "curr") DIFF=0;;
    "next") DIFF=$((DIFF+1));;
    "prev") DIFF=$((DIFF-1));;
    *) echo "Invalid action"; exit 1;;
esac
echo "$DIFF" > "$TMP"
TODAY=$(date '+%-d')
HEAD=$(cal "+$DIFF months" | head -n1)
BODY=$(cal "+$DIFF months" | tail -n7 | sed -z "s|$TODAY|<u><b>$TODAY</b></u>|1")
dunstify -h string:x-canonical-private-synchronous:calendar \
    "$HEAD" "$BODY" -u NORMAL -i null