#!/bin/bash
if command -v docker >/dev/null 2>&1; then
    running=$(docker ps -q | wc -l)
    if [ "$running" -gt 0 ]; then
        echo " ${running}"
    else
        echo " 0"
    fi
else
    echo ""
fi