Net/ThemeName "Nordic"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "Bibata-Classic"
Gtk/CursorThemeSize 24
Gtk/FontName "JetBrains Mono 10"
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
Xft/DPI 98304
